# Just docs specific configuration
logo: 'https://user-images.githubusercontent.com/11653294/64466233-7cd17480-d119-11e9-8965-e036c1e23c9a.png'
search_enabled: true
heading_anchors: true
back_to_top: true
back_to_top_text: 'Back to top'
aux_links:
    'SAP Cloud Platform Alert Notification node client on GitHub':
        - '//github.com/SAP/alert-notification-node-client'

title: SAP Cloud Platform Alert Notification Node client
baseurl: '/alert-notification-node-client' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
remote_theme: pmarsceill/just-the-docs
plugins:
    - github-pages
    - jekyll-feed
    - jekyll-include-cache
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
