# Just docs specific configuration
logo: 'https://img.shields.io/badge/Service_Documentation-@SAP%20Help%20Portal-ff9900.svg'
search_enabled: true
heading_anchors: true
back_to_top: true
back_to_top_text: 'Back to top'
aux_links:
    'SAP Cloud Platform Alert Notification node client on GitHub':
        - '//github.com/pmarsceill/just-the-docs'

title: SAP Cloud Platform Alert Notification Node client
description: >- # this means to ignore newlines until "baseurl:"
    Write an awesome description for your new site here. You can edit this
    line in _config.yml. It will appear in your document head meta (for
    Google search results) and in your feed.xml site description.
baseurl: '' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: just-the-docs
plugins:
    - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
